language: node_js
node_js:
 - "stable"

cache: 
  directories: 
    - "node_modules"    

after_success: npm run coverage
addons:
  code_climate:
      repo_token:
        secure: "XfscVgguClxek8Z9QhR4GqKQtODPjLdrWMFXytGt1Ld+l4qE7g6PdzJzOlBCIAc8VyHAihWnj/FueZpuND8VJ8PJoPLofrl+CdoB/iaA4Qav3h0rP/MYhesU8LbJxfSNMfChh2bZN3rKDJV1UMbs1P9onInOIFQ7gl3Rk5kQWU9lX8duCdiyu2gruGURy/9uST+y+ifX+sKXiVUwffePHWStbPcYTpS3y0yefZGbwI2nWlNOwpxm9lRsIE/pDzmmmyKZJUj3J5ZaqtnXVCMwEc4BOtQO1wViwLRpSB4yw7J18PM4HaQPbhKf+tWEupZD34ejUipAZ9r2Mlc7APnTlriUCH6DFO8BJLK9VYVPlInA0VB8tREW0IHmZDqkWdrp7DjEH+itpOYZuAkt1fGJSafE2o9EObT7Ne8vCg/bOhYV30yvCWG01TQFzpOgg7UEGYPFk3ZHe132VYDCt29pqNqREr16vC1Bs4u4qmNPSqy2H5JU5gBaqj7jyhwwlVdAhs6dcqNuvfSjf2tOsGo6WkZhxDoyPDynDIM/6FgdIDlyBsxWqu0JKNU39fE1ZBkjFa3nOUnJCEbh73PDVr9bXpZAgGYAx6uCuIEMyOzlnIqF9zP09wu1tWAohRxnHKhJr3r926LOFce1YcsdYAMNlUkOc0K5CjNl4yD97ysZ2i4="